### ISSUE TITLE
Add references to Relion 3 paper.

### ISSUE THREAD

**Issue by delarosatrevin** [delarosatrevin/scipion#30]
Add it to the package level.

**Comment by azazellochg** [comment]
I think it should be added to references for the whole plugin

**Comment by delarosatrevin** [comment]
Do we have the GPU acceleration paper reference?

**Comment by azazellochg** [comment]
I have added an issue here: https://github.com/scipion-em/scipion-em-relion/issues/5

**Comment by delarosatrevin** [comment]
Ok, I will close this one since that one is more complete.
