### ISSUE TITLE
New protocls of Relion 3.0 can't be detected (EXCEPT MULTIBODY)

### ISSUE THREAD

**Issue by vabrishami** [delarosatrevin/scipion#47]
**Describe the bug**

The new protocols of Relion 3.0 such as Bayesian Polishing do not appear in the tree viewer and even I can not find them using Search Protocol. Multibody refinement is the only protocol which appears in the tree viewer. 

**To Reproduce**
I followed the steps of "Testing Relion 3 in Scipion" and made a soft link to Relion 3.0 that we currently use, and after installing, I just run the Scipion.

**Expected behavior**
To see the new protocols of Relion 3.0 in the tree viewer or to search for them using Search Protocol.

**Screenshots**
![image](https://user-images.githubusercontent.com/9831418/52045650-a73ccd00-254d-11e9-98fb-84fbb2eb5fdc.png)

**Desktop**
 - OS: CentOS 6
 - Scipion: 1.2.2-rc (2019-01-28) Constantino (sdevel-relion3)

**Comment by delarosatrevin** [comment]
Hi @vabrishami , thanks for reporting. 
Have you modified the user configuration file to point to Relion 3 as well?

**Comment by vabrishami** [comment]
Hi @delarosatrevin 

So I made a soft link in software/em which points to my already installed Relion 3.0  and then changed Relion home to:

RELION_HOME = %(EM_ROOT)s/relion-3.0

**Comment by delarosatrevin** [comment]
Ok, then it is correct...the protocols should appear at least in the Search dialog.
I will take a look.

**Comment by andreanans** [comment]
Hi, I just ran the relion 3.0 test (worked fine), however I cannot search for any of the new relion-3.0 protocols. I double-checked that RELION_HOME points to relion-3.0.

**Comment by delarosatrevin** [comment]
Hi Andrea, yesterday I found same issue during a course in Helsinki and I
know how to fix it. I will get back to you later.

**Comment by delarosatrevin** [comment]
Hi @andreanans, 

The issue with Relion3 protocols not showing up, was due to the matching of relion version. There was a bug that was wrongly reporting version '2.1' despite having Relion 3 in the configuration files.

I have submitted the fix, along with other updates/fixes to my branch. You you can update with **git pull** and after that, you should be able to find the relion protocols. 

@vabrishami you could also undo the temporary fix there and update with latest changes.

I'm closing this issue, please let me know if it is working or no.

**Comment by andreanans** [comment]
Yep, I can see all of the protocols. Thanks! Will give it a try soon..
One quick question, if I want to do Bayesian polishing at this point do I have to use Relion's implementation of motioncor2? Is there a plan to write out the metadata star files after running the GPU version?

**Comment by delarosatrevin** [comment]
This is the beauty of Scipion...you can use any motion correction method that you want (e.g motioncor2, unblur, relion, etc) and later you can use the Bayesian Polishing...in the later, I create the proper .star files expected by Relion, taking the info of the shifts stored with the input movies.
